# Generated by Django 6.0.3 on 2026-04-19 22:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PatientInformation",
            fields=[
                (
                    "patient_id",
                    models.AutoField(
                        db_column="Patient_ID", primary_key=True, serialize=False
                    ),
                ),
                ("first_name", models.CharField(db_column="First_Name", max_length=50)),
                ("last_name", models.CharField(db_column="Last_Name", max_length=50)),
                (
                    "dob",
                    models.DateField(
                        blank=True,
                        db_column="DOB",
                        null=True,
                        verbose_name="Date of Birth",
                    ),
                ),
                (
                    "patient_type",
                    models.CharField(
                        choices=[("Male", "Male"), ("Female", "Female")],
                        db_column="Patient_Type",
                        max_length=6,
                    ),
                ),
                (
                    "sex_at_birth",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Male", "Male"),
                            ("Female", "Female"),
                            ("Intersex", "Intersex"),
                        ],
                        db_column="Sex_at_Birth",
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "patient_gender",
                    models.CharField(
                        blank=True, db_column="Patient_Gender", max_length=30, null=True
                    ),
                ),
                (
                    "treatment_plan",
                    models.TextField(blank=True, db_column="Treatment_Plan", null=True),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="patient_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Patient",
                "verbose_name_plural": "Patients",
                "db_table": "PatientInformation",
                "ordering": ["last_name", "first_name"],
            },
        ),
        migrations.CreateModel(
            name="FemalePatients",
            fields=[
                (
                    "patient",
                    models.OneToOneField(
                        db_column="Patient_ID",
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="female_data",
                        serialize=False,
                        to="patients.patientinformation",
                    ),
                ),
                (
                    "cycle_number",
                    models.IntegerField(blank=True, db_column="CycleNumber", null=True),
                ),
                (
                    "length_of_cycle",
                    models.IntegerField(
                        blank=True, db_column="LengthofCycle", null=True
                    ),
                ),
                (
                    "mean_cycle_length",
                    models.DecimalField(
                        blank=True,
                        db_column="MeanCycleLength",
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "estimated_day_of_ovulation",
                    models.IntegerField(
                        blank=True, db_column="EstimatedDayofOvulation", null=True
                    ),
                ),
                (
                    "reproductive_category",
                    models.IntegerField(
                        blank=True,
                        db_column="ReproductiveCategory",
                        help_text="0 = normal; see study coding for other values",
                        null=True,
                    ),
                ),
                (
                    "total_days_of_fertility",
                    models.IntegerField(
                        blank=True, db_column="TotalDaysofFertility", null=True
                    ),
                ),
                (
                    "mean_menses_length",
                    models.DecimalField(
                        blank=True,
                        db_column="MeanMensesLength",
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "total_menses_score",
                    models.IntegerField(
                        blank=True, db_column="TotalMensesScore", null=True
                    ),
                ),
                (
                    "unusual_bleeding",
                    models.BooleanField(
                        blank=True, db_column="UnusualBleeding", null=True
                    ),
                ),
                (
                    "numberpreg",
                    models.IntegerField(
                        blank=True,
                        db_column="Numberpreg",
                        null=True,
                        verbose_name="Number of pregnancies",
                    ),
                ),
                (
                    "livingkids",
                    models.IntegerField(
                        blank=True,
                        db_column="Livingkids",
                        null=True,
                        verbose_name="Living children",
                    ),
                ),
                (
                    "miscarriages",
                    models.IntegerField(
                        blank=True, db_column="Miscarriages", null=True
                    ),
                ),
                (
                    "abortions",
                    models.IntegerField(blank=True, db_column="Abortions", null=True),
                ),
                (
                    "breastfeeding",
                    models.BooleanField(
                        blank=True, db_column="Breastfeeding", null=True
                    ),
                ),
            ],
            options={
                "verbose_name": "Female Patient Record",
                "verbose_name_plural": "Female Patient Records",
                "db_table": "FemalePatients",
            },
        ),
        migrations.CreateModel(
            name="MalePatients",
            fields=[
                (
                    "patient",
                    models.OneToOneField(
                        db_column="Patient_ID",
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="male_data",
                        serialize=False,
                        to="patients.patientinformation",
                    ),
                ),
                (
                    "trauma_history",
                    models.BooleanField(
                        blank=True, db_column="Trauma_History", null=True
                    ),
                ),
                (
                    "fever_history",
                    models.CharField(
                        blank=True, db_column="Fever_History", max_length=50, null=True
                    ),
                ),
                (
                    "activity_levels",
                    models.DecimalField(
                        blank=True,
                        db_column="Activity_Levels",
                        decimal_places=1,
                        help_text="Hours spent sitting per day",
                        max_digits=4,
                        null=True,
                    ),
                ),
                (
                    "diagnosis",
                    models.CharField(
                        blank=True,
                        db_column="Diagnosis",
                        help_text="Normal or Altered",
                        max_length=20,
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Male Patient Record",
                "verbose_name_plural": "Male Patient Records",
                "db_table": "MalePatients",
            },
        ),
        migrations.CreateModel(
            name="PatientMedicalHistory",
            fields=[
                (
                    "patient",
                    models.OneToOneField(
                        db_column="Patient_ID",
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="medical_history",
                        serialize=False,
                        to="patients.patientinformation",
                    ),
                ),
                (
                    "diabetes_status",
                    models.CharField(
                        blank=True,
                        db_column="Diabetes_Status",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "height",
                    models.DecimalField(
                        blank=True,
                        db_column="Height",
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "weight",
                    models.DecimalField(
                        blank=True,
                        db_column="Weight",
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "blood_type",
                    models.CharField(
                        blank=True, db_column="Blood_Type", max_length=5, null=True
                    ),
                ),
                (
                    "medical_conditions",
                    models.TextField(
                        blank=True, db_column="Medical_Conditions", null=True
                    ),
                ),
                (
                    "surgical_history",
                    models.TextField(
                        blank=True, db_column="Surgical_History", null=True
                    ),
                ),
                (
                    "alcohol_use",
                    models.CharField(
                        blank=True, db_column="Alcohol_Use", max_length=50, null=True
                    ),
                ),
            ],
            options={
                "verbose_name": "Medical History",
                "verbose_name_plural": "Medical Histories",
                "db_table": "PatientMedicalHistory",
            },
        ),
    ]
