# Generated by Django 6.0.3 on 2026-04-28 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="patientinformation",
            name="patient_role",
            field=models.CharField(
                choices=[("Client", "Client"), ("Donor", "Donor")],
                db_column="Patient_Role",
                default="Client",
                max_length=6,
            ),
        ),
    ]
